#!/bin/bash

mkdir tools

# Install deps 
sudo dnf install git ansible 

# Run ansible playbook
sudo ansible-pull -U https://github.com/tomncooper/dotfiles.git

# Install the offline upgrade plugin for dnf
dnf install 'dnf-command(offline-upgrade)'

# Make sure the local config file is there
touch .zsh_local

# Install oh my zsh
sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

# Copy the solarized theme to to the vim folder
mkdir -p $HOME/.vim/colors
wget https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim -P $HOME/.vim/colors

# Add the zsh-syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Install SDK man 
curl -s "https://get.sdkman.io" | bash

# Install Vim Anywhere
curl -fsSL https://raw.github.com/cknadler/vim-anywhere/master/install | bash

# Pull fzf-git
curl -s https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh -o tools/fzf-git.sh
