---
- import_playbook: local.yml
- hosts: localhost
  become: true
  tasks:
    - name: Install native packages
      dnf: name={{item}}
      with_items:
        - arandr
        - lxpolkit
        - pasystray
        - feh
        - copyq
        - ranger
        - w3m
        - w3m-img
        - rofi
        - polybar
        - light
        - playerctl
