- import_playbook: fedora.yml
- hosts: localhost
  become: true
  tasks:
    - name: Add the Hashicorp repo
      ansible.builtin.yum_repository:
        name: hashicorp-stable
        description: Hashicorp Stable Repository
        baseurl: https://rpm.releases.hashicorp.com/RHEL/9/$basearch/stable
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        gpgcheck: 1
        enabled: 1
    - name: Add the GCloud repo
      ansible.builtin.yum_repository:
        name: gcloud-cli
        description: GCloud CLI Repository
        baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: 1
        enabled: 1
        repo_gpgcheck: 0
    - name: Add the Cloudflare Warp repo
      ansible.builtin.yum_repository:
        name: cloudflare-warp-stable
        description: Cloudflare Warp Repository
        baseurl: https://pkg.cloudflareclient.com/rpm
        gpgkey: https://pkg.cloudflareclient.com/pubkey.gpg
        gpgcheck: 1
        enabled: 1
    - name: Install native packages
      dnf: name={{item}}
      with_items:
        - terraform
        - packer
        - puppet
        - go-task
        - helm
        - ansible-lint
        - protobuf-compiler
        - google-cloud-cli
        - cloudflare-warp
    - name: Install flatpak packages
      community.general.flatpak:
        name:
          - us.zoom.Zoom
