- hosts: localhost
  become: true
  tasks:
    - name: Add the bottom (resource monitor) repo
      community.general.copr:
        state: enabled
        name: atim/bottom
    - name: Install native packages
      dnf: name={{item}}
      with_items:
        - zsh
        - zsh-syntax-highlighting
        - vim
        - eza
        - bat
        - fzf
        - yadm
        - ipython
        - python-poetry
        - bottom
        - gh
        - kubernetes-client
