- import_playbook: base-repos.yml
- hosts: localhost
  become: true
  tasks:
    - name: Install native packages
      dnf: name={{item}}
      with_items:
        - zsh
        - zsh-syntax-highlighting
        - vim
        - eza
        - bat
        - fzf
        - yadm
        - ipython
        - python-poetry
        - bottom
        - gh
        - kubernetes-client
        - code
