# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[username]
disabled = false
show_always = true
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) on '

[hostname]
disabled = false
ssh_only = false
style = 'bold green'
aliases = { "li-02f403cc-2d94-11b2-a85c-a8e0a2bff2c0" = "ibm-laptop" }
